# example values

indexing-settings:
  siteUrls:
    - url: https://www.yourhtmlsource.com
      name: МикроСайт
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

spring:
  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    url: jdbc:mysql://localhost:3306/indexing
    username: root
    password: mysql

  jpa:
    properties:
      hibernate:
        show_sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update

  mvc:
    hidden-method:
      filter:
        enabled: true