indexing-settings:
  siteUrls:
    - url: https://psiholog-chirkina-yana.ru
      name: ПСИХОЛОГ ЯНА ЧИРКИНА
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
  parsingDelay: 1

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/index_db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  mvc:
    hidden-method:
      filter:
        enabled: true

logging:
  level:
    engine: debug
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
